### ISSUE TITLE
Minor update fixes issue with sending name as empty string

### ISSUE THREAD

**Issue by Magiweb** [dogusev/getresponse-nodejs-api#1]
Hey @dogusev,

Stumbled onto an issue where if you don't define the subscriber's name, you're sending through a blank "name" parameter, which Getresponse rejects as a bad request. If the name isn't defined it should not be sent as a parameter at all - unfortunately it's not sufficient to simply set it to an empty string. 

I've modified one line of your code slightly and now it works perfectly: 

Changed node_modules/getresponse-nodejs-api/lib/getResponse.js line 575 to:

  $name ? params[ 'name' ] = $name : '';

Would you minde making the change and pushing the update?

**Comment by dogusev** [comment]
Hi @Magiweb !
Thank you for help.
I didn't find such code on line 575. Maybe it's on different line?

Also at line 535 there is 
params['name'] = $name || '';

Could you sumbit a pull request? I'll merge it and update the npm module also.
Or please provide more details.

**Comment by Magiweb** [comment]
@dogusev you're right it's 535!

I'll do the change if you want

**Comment by dogusev** [comment]
@Magiweb
merged.
Also npm module updated.
Thank you!
